# Generated by Django 5.0 on 2024-12-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('practice_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='chambers_logos/')),
                ('website', models.URLField(blank=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('subscription_status', models.CharField(choices=[('TRIAL', 'Free Trial'), ('LISTING', 'Listing'), ('GROWTH', 'Growth')], default='TRIAL', max_length=20)),
                ('trial_leads_remaining', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_chambers', to='accounts.user')),
                ('practice_areas', models.ManyToManyField(related_name='chambers', to='practice_areas.practicearea')),
            ],
            options={
                'verbose_name_plural': 'chambers',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('chambers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='chambers.chambers')),
                ('practice_areas', models.ManyToManyField(related_name='offices', to='practice_areas.practicearea')),
            ],
        ),
    ]
