# Generated by Django 5.0 on 2024-12-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chambers', '0001_initial'),
        ('practice_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_direct_access', models.BooleanField(default=False)),
                ('year_of_call', models.IntegerField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('subscription_status', models.CharField(choices=[('TRIAL', 'Free Trial'), ('LISTING', 'Listing'), ('GROWTH', 'Growth')], default='TRIAL', max_length=20)),
                ('trial_leads_remaining', models.IntegerField(default=5)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chambers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barristers', to='chambers.chambers')),
                ('practice_areas', models.ManyToManyField(related_name='barristers', to='practice_areas.practicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barrister_profile', to='accounts.user')),
            ],
        ),
    ]
