# Generated by Django 5.0 on 2024-12-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('barristers', '0001_initial'),
        ('chambers', '0001_initial'),
        ('practice_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('instruction_type', models.CharField(choices=[('HEARING', 'Hearing'), ('TRIAL', 'Trial'), ('ADVICE', 'Advice'), ('DRAFTING', 'Drafting Pleadings')], max_length=50)),
                ('court', models.CharField(blank=True, max_length=255)),
                ('claim_number', models.CharField(blank=True, max_length=100)),
                ('hearing_length', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barristers', models.ManyToManyField(blank=True, related_name='received_enquiries', to='barristers.barrister')),
                ('chambers', models.ManyToManyField(blank=True, related_name='received_enquiries', to='chambers.chambers')),
                ('practice_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice_areas.practicearea')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_enquiries', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
